export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const GET_SVALUE_REQUEST = "GET_SVALUE_REQUEST";
export const GET_SVALUE_SUCCESS = "GET_SVALUE_SUCCESS";
export const GET_SVALUE_FAILURE = "GET_SVALUE_FAILURE";
export const SEACH_BY_NAME = "SEARCH_BY_NAME";